version: "3.3"
services:
  postgres:
    image: 'postgres:14-alpine'
    restart: always
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - '../data/HomeSpendingsProject:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=spendings
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'